# Generated by Django 2.2.7 on 2020-03-20 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('prefix', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prefix')),
                ('suffix', models.CharField(blank=True, max_length=50, null=True, verbose_name='Suffix')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kennels',
                'db_table': 'kennel',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('mi', models.CharField(blank=True, max_length=50, null=True, verbose_name='MI')),
                ('kennel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kennel', to='organizer.Kennel', verbose_name='kennel')),
            ],
            options={
                'verbose_name_plural': 'People',
                'db_table': 'person',
            },
        ),
    ]
