# Generated by Django 2.2.7 on 2020-03-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20200320_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='kennel',
            name='country',
            field=models.CharField(blank=True, default='USA', max_length=3, null=True),
        ),
    ]
