# Generated by Django 2.2.10 on 2020-03-30 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20200330_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kennel',
            name='country',
        ),
    ]
