# Generated by Django 2.2.10 on 2020-04-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_auto_20200330_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='akc_bred_with_heart',
            field=models.BooleanField(default=False, verbose_name='AKC Bred with H.E.A.R.T'),
        ),
        migrations.AddField(
            model_name='person',
            name='akc_breeder_of_merit',
            field=models.BooleanField(default=False, verbose_name='AKC Breeder of Merit'),
        ),
        migrations.AlterField(
            model_name='kennel',
            name='fb_url',
            field=models.URLField(blank=True, default='', verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='kennel',
            name='web_url',
            field=models.URLField(blank=True, default='', verbose_name='Website'),
        ),
    ]
