# Generated by Django 2.2.10 on 2020-04-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_auto_20200406_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='yr_started',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Started'),
        ),
    ]
