# Generated by Django 2.2.10 on 2020-04-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_person_yr_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kennel',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='person',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Comments'),
        ),
    ]
