# Generated by Django 2.2.10 on 2020-03-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50, verbose_name='Model Field')),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
                ('text', models.CharField(max_length=50, verbose_name='Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name_plural': 'Choices',
                'db_table': 'choice',
                'ordering': ['field', 'code', 'text'],
            },
        ),
    ]
