# Generated by Django 2.2.10 on 2020-03-25 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='slug',
        ),
    ]
