# Generated by Django 2.2.10 on 2020-03-30 20:31

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poodle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, populate_from='name_registered', unique=True)),
                ('name_call', models.CharField(max_length=50, verbose_name='Call Name')),
                ('name_registered', models.CharField(max_length=50, verbose_name='Registered Name')),
                ('akc', models.CharField(max_length=50, verbose_name='AKC#')),
                ('chic', models.CharField(blank=True, default='', max_length=50, verbose_name='CHIC#')),
                ('ukc', models.CharField(blank=True, default='', max_length=50, verbose_name='UKC#')),
                ('is_altered', models.BooleanField(default=False, verbose_name='Altered?')),
                ('dob', models.DateField(blank=True, default='', null=True, verbose_name='Date of Birth')),
                ('dod', models.DateField(blank=True, default='', null=True, verbose_name='Date of Death')),
                ('titles_prefix', models.CharField(blank=True, default='', max_length=50, verbose_name='Prefix Titles')),
                ('titles_suffix', models.CharField(blank=True, default='', max_length=50, verbose_name='Suffix Titles')),
                ('comments', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('person_breeders', models.ManyToManyField(blank=True, related_name='poodles_breeders', to='organizer.Person', verbose_name='Breeder(s)')),
                ('person_owners', models.ManyToManyField(blank=True, related_name='poodles_owners', to='organizer.Person', verbose_name='Owner(s)')),
                ('poodle_dam', models.ForeignKey(blank=True, limit_choices_to={'sex': 'F'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poodles_dam', to='poodles.Poodle', verbose_name='Dam')),
                ('poodle_sire', models.ForeignKey(blank=True, limit_choices_to={'sex': 'M'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poodles_sire', to='poodles.Poodle', verbose_name='Sire')),
            ],
            options={
                'verbose_name_plural': 'Poodles',
                'db_table': 'poodle',
                'ordering': ['name_call'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('path', models.ImageField(upload_to='images/')),
                ('is_viewable', models.BooleanField(default=True, verbose_name='Viewable?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('poodle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poodles_images', to='poodles.Poodle', verbose_name='Poodle')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('path', models.FileField(upload_to='documents/')),
                ('is_viewable', models.BooleanField(default=True, verbose_name='Viewable?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('poodle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poodles_documents', to='poodles.Poodle', verbose_name='Poodle')),
            ],
        ),
    ]
