# Generated by Django 2.2 on 2020-03-16 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('mi', models.CharField(blank=True, max_length=50, null=True, verbose_name='MI')),
                ('kennel_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kennel')),
                ('kennel_prefix', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prefix')),
                ('kennel_suffix', models.CharField(blank=True, max_length=50, null=True, verbose_name='Suffix')),
            ],
            options={
                'verbose_name_plural': 'People',
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Poodle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_call', models.CharField(max_length=50, verbose_name='Call Name')),
                ('name_registered', models.CharField(max_length=50, verbose_name='Registered Name')),
                ('akc', models.CharField(max_length=50, verbose_name='AKC#')),
                ('chic', models.CharField(blank=True, max_length=50, null=True, verbose_name='CHIC#')),
                ('ukc', models.CharField(blank=True, max_length=50, null=True, verbose_name='UKC#')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Dog'), ('F', 'Bitch')], max_length=1, null=True)),
                ('is_altered', models.BooleanField(default=False, verbose_name='Altered?')),
                ('color', models.CharField(blank=True, choices=[('MP', 'Multi/Parti'), ('WH', 'White'), ('BL', 'Black'), ('BU', 'Blue')], max_length=2, null=True, verbose_name='Color')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('dod', models.DateField(blank=True, null=True, verbose_name='Date of Death')),
                ('titles_prefix', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prefix Titles')),
                ('titles_suffix', models.CharField(blank=True, max_length=50, null=True, verbose_name='Suffix Titles')),
                ('person_breeders', models.ManyToManyField(related_name='breeders', to='poodles.Person', verbose_name='Breeder(s)')),
                ('person_owners', models.ManyToManyField(related_name='owners', to='poodles.Person', verbose_name='Owner(s)')),
                ('poodle_dam', models.ForeignKey(blank=True, limit_choices_to={'sex': 'F'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dam', to='poodles.Poodle', verbose_name='Dam')),
                ('poodle_sire', models.ForeignKey(blank=True, limit_choices_to={'sex': 'M'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sire', to='poodles.Poodle', verbose_name='Sire')),
            ],
            options={
                'verbose_name_plural': 'Poodles',
                'db_table': 'poodle',
            },
        ),
    ]
