# Generated by Django 2.2.10 on 2020-03-24 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poodles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poodle',
            options={'ordering': ['name_call'], 'verbose_name_plural': 'Poodles'},
        ),
        migrations.AddField(
            model_name='poodle',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='poodle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poodle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='poodle',
            name='chic',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='CHIC#'),
        ),
        migrations.AlterField(
            model_name='poodle',
            name='color',
            field=models.CharField(choices=[('MP', 'Multi/Parti'), ('WH', 'White'), ('BL', 'Black'), ('BU', 'Blue'), ('U', 'Unknown')], default='U', max_length=2, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='poodle',
            name='person_breeders',
            field=models.ManyToManyField(blank=True, related_name='poodles_breeders', to='organizer.Person', verbose_name='Breeder(s)'),
        ),
        migrations.AlterField(
            model_name='poodle',
            name='person_owners',
            field=models.ManyToManyField(blank=True, related_name='poodles_owners', to='organizer.Person', verbose_name='Owner(s)'),
        ),
        migrations.AlterField(
            model_name='poodle',
            name='poodle_dam',
            field=models.ForeignKey(blank=True, limit_choices_to={'sex': 'F'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poodles_dam', to='poodles.Poodle', verbose_name='Dam'),
        ),
        migrations.AlterField(
            model_name='poodle',
            name='poodle_sire',
            field=models.ForeignKey(blank=True, limit_choices_to={'sex': 'M'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poodles_sire', to='poodles.Poodle', verbose_name='Sire'),
        ),
        migrations.AlterField(
            model_name='poodle',
            name='sex',
            field=models.CharField(choices=[('M', 'Dog'), ('F', 'Bitch')], default='M', max_length=1, verbose_name='Sex'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poodle',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, populate_from='name_registered', unique=True),
        ),
        migrations.AlterField(
            model_name='poodle',
            name='titles_prefix',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Prefix Titles'),
        ),
        migrations.AlterField(
            model_name='poodle',
            name='titles_suffix',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Suffix Titles'),
        ),
        migrations.AlterField(
            model_name='poodle',
            name='ukc',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='UKC#'),
        ),
    ]
