# Generated by Django 2.2.10 on 2020-04-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poodles', '0002_auto_20200330_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='poodle',
            name='addtl',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Additional #'),
        ),
        migrations.AlterField(
            model_name='poodle',
            name='color',
            field=models.CharField(choices=[('BL', 'Black'), ('BU', 'Blue'), ('CR', 'Cream'), ('MP', 'Multi/Parti'), ('U', 'Unknown'), ('WH', 'White')], default='U', max_length=2, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='poodle',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Comments'),
        ),
    ]
