# Generated by Django 2.2.10 on 2020-04-22 21:01

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poodles', '0004_auto_20200422_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from=['poodle__name_call', 'title', 'id'], unique=True),
        ),
    ]
