# Generated by Django 2.2.10 on 2020-03-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poodles', '0005_auto_20200324_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doc_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='path',
        ),
        migrations.AddField(
            model_name='document',
            name='is_viewable',
            field=models.BooleanField(default=True, verbose_name='Altered?'),
        ),
        migrations.AddField(
            model_name='image',
            name='is_viewable',
            field=models.BooleanField(default=True, verbose_name='Altered?'),
        ),
    ]
